### ISSUE TITLE
SIM-1 | Computer Simulation Plan

### ISSUE THREAD

**Issue by SamsonKaller** [salhanyf/iSeat-COEN390#12]
## Story points: 
40

### The Card

- [ ] Discover the minimum reliable configuration for the sensors on seats. 

Options:
- 1 sensor centered/back of seat
- 3 sensors in a circular pattern
- 4 sensors in a square pattern

- [ ] Create 3-D surface plots of seats, sensors, and students in software (SolidWorks or similar).

- [ ] Test contact/overlap between student and sensor(s) on the seat using various seat sizes, sensor positions, and student shapes.

#### Child Stories:
#13 #14 #15 #16
